### ISSUE TITLE
Ignition OPC Item Path

### ISSUE THREAD

**Issue by visionarymlm** [ductsoup/ModbusTCP#1]
I was wondering what Item path you used when using Ignition. I have not been able to read the response from the slave. The connection is good and I can see the slave responding. 
I have got Ignition to work with "Mudbus" using "[modbus_Slave]HR1" as the path. 
I am using the example project with an Uno and w5100 ethernet shield.

**Comment by ductsoup** [comment]
It looks like you have a typo in your path. In Ignition the procedure is the same as adding any other modbus device. 

Confirm your slave is working properly with modpoll or something like it. Then add the device to Ignition, map the register addresses and types you setup in the slave. Finally check that everything is working as expected using the quick client.

**Comment by visionarymlm** [comment]
Thanks for the quick reply. My typo was only in the message, not in ignition. I will try modpoll to make sure the slave is working.
